# Generated by Django 5.2.9 on 2026-01-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('summary', models.TextField(max_length=500, verbose_name='Resumo')),
                ('content', models.TextField(verbose_name='Conteúdo completo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Imagem da notícia')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque na Home')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-created_at'],
            },
        ),
    ]
