# Generated by Django 6.0 on 2026-01-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoSocialCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[('aberto', 'Processo Seletivo Aberto'), ('fechado', 'Processo Seletivo Fechado')], default='fechado', max_length=10, verbose_name='Status')),
                ('form_link', models.URLField(blank=True, null=True, verbose_name='Link do formulário (Microsoft Forms)')),
                ('opening_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data de abertura')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Card do Código Social',
                'verbose_name_plural': 'Cards do Código Social',
                'ordering': ['-created_at'],
            },
        ),
    ]
