# Generated by Django 6.0 on 2026-01-29 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_codigosocialcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeletivoHealthtech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado')], default='fechado', max_length=10)),
                ('form_link', models.URLField(blank=True, help_text='Link do Microsoft Forms (apenas se estiver aberto)', null=True)),
                ('expected_date', models.CharField(blank=True, help_text='Ex: Agosto de 2026 (usado se estiver fechado)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
