# Generated by Django 6.0 on 2026-01-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seletivohealthtech'),
    ]

    operations = [
        migrations.AddField(
            model_name='seletivohealthtech',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='seletivohealthtech',
            name='expected_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='seletivohealthtech',
            name='form_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seletivohealthtech',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado')], max_length=10),
        ),
    ]
