# Generated by Django 6.0 on 2026-01-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seletivohealthtech_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seletivohealthtech',
            name='expected_date',
        ),
        migrations.AddField(
            model_name='seletivohealthtech',
            name='opening_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Data de abertura'),
        ),
        migrations.AlterField(
            model_name='seletivohealthtech',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='seletivohealthtech',
            name='form_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link do formulário (Microsoft Forms)'),
        ),
        migrations.AlterField(
            model_name='seletivohealthtech',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='seletivohealthtech',
            name='status',
            field=models.CharField(choices=[('aberto', 'Processo Seletivo Aberto'), ('fechado', 'Processo Seletivo Fechado')], default='fechado', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='seletivohealthtech',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
