# Generated by Django 6.0 on 2026-01-29 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_seletivohealthtech_expected_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SeletivoHealthtech',
            new_name='HealthcareJuniorCard',
        ),
        migrations.AlterModelOptions(
            name='healthcarejuniorcard',
            options={'ordering': ['-created_at'], 'verbose_name': 'Card da Healthcare Júnior Einstein', 'verbose_name_plural': 'Cards da Healthcare Júnior Einstein'},
        ),
    ]
