# Generated by Django 6.0 on 2026-01-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_news_options_remove_news_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='external_link',
            field=models.URLField(blank=True, help_text='Link externo relacionado à notícia (opcional)', null=True),
        ),
    ]
