# Generated by Django 6.0 on 2026-01-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_news_external_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('healthcare', 'Healthtech Júnior'), ('social', 'Código Social')], default='healthcare', max_length=20, verbose_name='Categoria')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[('aberto', 'Processo Seletivo Aberto'), ('fechado', 'Processo Seletivo Fechado')], default='fechado', max_length=10, verbose_name='Status')),
                ('form_link', models.URLField(blank=True, null=True, verbose_name='Link do formulário')),
                ('opening_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data de abertura')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Processo Seletivo',
                'verbose_name_plural': 'Processos Seletivos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CodigoSocialCard',
        ),
        migrations.DeleteModel(
            name='HealthcareJuniorCard',
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notícia', 'verbose_name_plural': 'Notícias'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
        migrations.AddField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última atualização'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(verbose_name='Conteúdo completo'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='news',
            name='external_link',
            field=models.URLField(blank=True, help_text='Link externo relacionado à notícia (opcional)', null=True, verbose_name='Link externo'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Destaque na Home'),
        ),
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.TextField(max_length=500, verbose_name='Resumo'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link do Projeto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.TextField(verbose_name='Resumo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
