# Generated by Django 5.2 on 2026-03-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_project_is_featured"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
                ("photo", models.ImageField(upload_to="team/")),
                ("linkedin", models.URLField(blank=True, null=True)),
                ("instagram", models.URLField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
