# Generated by Django 5.2 on 2026-03-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_teammember"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="github",
            field=models.URLField(blank=True, null=True),
        ),
    ]
