# Generated by Django 5.2 on 2026-03-10 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_teammember_github"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teammember",
            name="instagram",
        ),
    ]
