# Generated by Django 5.2 on 2026-03-10 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_eventos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="team/"),
        ),
    ]
