# Generated by Django 5.2 on 2026-03-13 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_teammember_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodigoSocialFoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foto", models.ImageField(upload_to="codigo_social/")),
                ("legenda", models.CharField(blank=True, max_length=200)),
                ("ordem", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["ordem"],
            },
        ),
    ]
