# Generated by Django 5.2 on 2026-03-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_codigosocialfoto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventos",
            name="summary",
            field=models.TextField(max_length=300, verbose_name="Resumo"),
        ),
    ]
