# Generated by Django 5.2 on 2026-03-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_eventos_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventos",
            name="summary",
            field=models.TextField(max_length=550, verbose_name="Resumo"),
        ),
    ]
